version: '3.8'
services:
    redis:
        container_name: ReaderLand-redis
        image: redis:6.2.6
        restart: always
        networks:
            - ReaderLand-server-network

    ReaderLand:
        container_name: ReaderLand-server
        image: readerland:latest
        restart: always
        networks:
            - ReaderLand-server-network
        env_file:
            - .env
        depends_on:
            - redis

    nginx:
        container_name: ReaderLand-nginx
        image: nginx:alpine
        restart: always
        ports:
            - '80:80'
        networks:
            - ReaderLand-server-network
        volumes:
            - /home/ec2-user/Project/ReaderLand_docker_volumes/nginx:/etc/nginx
        depends_on:
            - ReaderLand

networks:
    ReaderLand:
        name: ReaderLand-server-network
        driver: bridge
