version: '3.8'
services:
    redis:
        container_name: ReaderLand-redis
        image: redis:6.2.6
        restart: always
        networks:
            - ReaderLand-server-network

    ReaderLand:
        container_name: ReaderLand-server
        image: readerland:latest
        restart: always
        networks:
            - ReaderLand-server-network
        env_file:
            - .env-dockercompose
        depends_on:
            - redis
        ports:
            - '3000:3000'

    nginx:
        container_name: ReaderLand-nginx
        image: nginx:alpine
        restart: always
        ports:
            - '80:80'
            - '443:443'
        networks:
            - ReaderLand-server-network
        volumes:
            - /home/ec2-user/docker-nginx:/etc/nginx
        depends_on:
            - ReaderLand

networks:
    ReaderLand-server-network:
        name: ReaderLand-server-network
        driver: bridge
