name: ReaderLand docker-env CI

on:
    push:
        branches: [docker-cicd]

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ contains(github.event.head_commit.message, '#CI') }}
        steps:
            - name: deploy to ec2
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_KEY }}
                  port: ${{ secrets.EC2_PORT }}
                  script: |
                      cd /home/ec2-user/Project/ReaderLand
                      docker-compose down
                      docker container prune -f
                      docker rmi readerland
                      docker-compose up
